DELETE FROM pkl_listings;

INSERT INTO pkl_listings (id, company, initials, logo_bg, location, "workMode", title, tags, description, major, is_open, "order", created_at, updated_at) VALUES
('pkl-rpl-1', 'Telkom Indonesia', 'TI', 'bg-[#E4002B]', 'Bandung', 'Hybrid', 'Frontend Developer Intern', ARRAY['React', 'TypeScript', 'Tailwind CSS', 'REST APIs'], 'Membantu pengembangan antarmuka portal layanan pelanggan berbasis web dan integrasi API design system Telkom.', 'RPL', true, 1, NOW(), NOW()),
('pkl-rpl-2', 'Finnet Indonesia', 'FN', 'bg-[#0761C7]', 'Jakarta', 'Hybrid', 'Backend Node.js & API Intern', ARRAY['Node.js', 'Express', 'PostgreSQL', 'REST APIs'], 'Mengembangkan endpoint microservice pembayaran digital, integrasi gateway perbankan, dan optimasi query database.', 'RPL', true, 2, NOW(), NOW()),
('pkl-rpl-3', 'Telkomsel', 'TS', 'bg-[#E4002B]', 'Jakarta', 'Hybrid', 'Mobile Flutter Developer Intern', ARRAY['Flutter', 'Dart', 'State Management', 'Mobile UI'], 'Membantu pembuatan fitur aplikasi mobile layanan mandiri pelanggan, pengujian widget, dan integrasi response API backend.', 'RPL', true, 3, NOW(), NOW()),
('pkl-rpl-4', 'Tokopedia', 'TP', 'bg-[#10B981]', 'Jakarta', 'Remote', 'Junior Fullstack Web Intern', ARRAY['Next.js', 'TypeScript', 'Prisma', 'Tailwind CSS'], 'Berkolaborasi dalam pengembangan fitur merchant dashboard, pemeliharaan arsitektur frontend, dan integrasi backend modern.', 'RPL', true, 4, NOW(), NOW()),
('pkl-rpl-5', 'Infomedia Nusantara', 'IN', 'bg-[#0761C7]', 'Bandung', 'Hybrid', 'QA Automation & Software Tester Intern', ARRAY['Playwright', 'Cypress', 'Jest', 'Manual Testing'], 'Menyusun skenario pengujian end-to-end, melakukan automation test antarmuka web, dan mendokumentasikan temuan bug sistem.', 'RPL', true, 5, NOW(), NOW()),

('pkl-tkj-1', 'Telkomsigma', 'TS', 'bg-[#E4002B]', 'Semarang', 'On-site', 'Data Center Support Intern', ARRAY['Linux Server', 'Monitoring', 'Hardware', 'Virtualization'], 'Membantu pemantauan operasional pusat data tier-3, inventarisasi server rak, dan dasar administrasi infrastruktur cloud enterprise.', 'TKJ', true, 6, NOW(), NOW()),
('pkl-tkj-2', 'PINS Indonesia', 'PN', 'bg-[#0761C7]', 'Purwokerto', 'On-site', 'IT Infrastructure & Support Intern', ARRAY['Jaringan', 'Hardware', 'Troubleshoot', 'MikroTik'], 'Mendukung instalasi perangkat jaringan, konfigurasi router/switch, dan perbaikan perangkat keras di lingkungan klien korporat.', 'TKJ', true, 7, NOW(), NOW()),
('pkl-tkj-3', 'Lintasarta', 'LA', 'bg-[#0761C7]', 'Jakarta', 'On-site', 'Network Engineer & Routing Intern', ARRAY['Cisco', 'MikroTik', 'BGP', 'VLAN', 'Routing'], 'Membantu konfigurasi routing static & dynamic, manajemen VLAN switch enterprise, dan pengawasan link WAN pelanggan bisnis.', 'TKJ', true, 8, NOW(), NOW()),
('pkl-tkj-4', 'Telkomsel Regional', 'TR', 'bg-[#E4002B]', 'Purwokerto', 'On-site', 'NOC Network Operations Intern', ARRAY['NOC', 'Wireshark', 'Monitoring', 'TCP/IP', 'Incident'], 'Membantu monitoring real-time ketersediaan jaringan telekomunikasi seluler dan koordinasi eskalasi insiden BTS di regional Jateng.', 'TKJ', true, 9, NOW(), NOW()),
('pkl-tkj-5', 'CBN Cloud', 'CB', 'bg-[#10B981]', 'Jakarta', 'Hybrid', 'Cloud & Linux Systems Admin Intern', ARRAY['Ubuntu Server', 'Docker', 'Nginx', 'Bash', 'Cloud'], 'Membantu konfigurasi web server Nginx, containerisasi aplikasi berbasis Docker, dan otomasi pemeliharaan server Linux.', 'TKJ', true, 10, NOW(), NOW()),

('pkl-tja-1', 'Telkom Akses Purwokerto', 'TA', 'bg-[#0761C7]', 'Purwokerto', 'On-site', 'Fiber Optic Splicing & OTDR Technician', ARRAY['FTTH', 'OTDR', 'Fusion Splicer', 'ODP/ODC'], 'Praktik langsung penanganan jaringan kabel serat optik, penyambungan core dengan fusion splicer, dan pengukuran redaman OTDR.', 'TJA', true, 11, NOW(), NOW()),
('pkl-tja-2', 'Telkom Akses Regional', 'TA', 'bg-[#0761C7]', 'Semarang', 'On-site', 'FTTH Outside Plant (OSP) Planner Intern', ARRAY['AutoCAD', 'QGIS', 'FTTH', 'Survey', 'ODP'], 'Membantu survei lapangan jalur distribusi kabel optik, pemetaan rute tiang & manhole, serta penggambaran as-built drawing jaringan FTTH.', 'TJA', true, 12, NOW(), NOW()),
('pkl-tja-3', 'Mitratel', 'MT', 'bg-[#E4002B]', 'Purwokerto', 'On-site', 'Tower & RF Transmission Technician Intern', ARRAY['Tower BTS', 'RF', 'Antenna', 'VSWR', 'K3 Lapangan'], 'Mendampingi teknisi senior dalam pemeliharaan berkala infrastruktur menara BTS, pengecekan feeder kabel RF, dan audit grounding.', 'TJA', true, 13, NOW(), NOW()),
('pkl-tja-4', 'Telkom Akses Banyumas', 'TA', 'bg-[#0761C7]', 'Purwokerto', 'On-site', 'Quality Assurance & Fiber Testing Intern', ARRAY['OPM', 'VFL', 'Optical Power', 'Fiber Optic'], 'Melakukan pengujian kualitas sambungan kabel optik pada jaringan backbone dan distribusi menggunakan Optical Power Meter (OPM) dan Visual Fault Locator.', 'TJA', true, 14, NOW(), NOW()),
('pkl-tja-5', 'Indosat Ooredoo Hutchison', 'IO', 'bg-[#F59E0B]', 'Yogyakarta', 'Hybrid', 'Microwave & Backhaul Transmission Intern', ARRAY['Microwave', 'Backhaul', 'Link Budget', 'Transmisi'], 'Membantu analisis performa link transmisi microwave antar-site, pemantauan utilisasi kapasitas backhaul radio, dan pelaporan metrik sinyal.', 'TJA', true, 15, NOW(), NOW()),

('pkl-pg-1', 'Agate International', 'AG', 'bg-[#8B5CF6]', 'Bandung', 'Hybrid', 'Game Programmer Unity & C# Intern', ARRAY['Unity', 'C#', 'Gameplay Mechanics', 'Physics 2D/3D'], 'Mengembangkan logika mekanisme gameplay, sistem kontrol karakter, dan integrasi antarmuka game menggunakan Unity Engine.', 'PG', true, 16, NOW(), NOW()),
('pkl-pg-2', 'Gameloft Indonesia', 'GL', 'bg-[#0761C7]', 'Yogyakarta', 'Hybrid', '3D Game Environment Artist Intern', ARRAY['Blender', 'Maya', '3D Modeling', 'Texturing', 'PBR'], 'Membuat aset lingkungan 3D berstandar mobile gaming, pemodelan low-poly teroptimasi, serta UV unwrapping dan texturing PBR.', 'PG', true, 17, NOW(), NOW()),
('pkl-pg-3', 'Nuon Digital Indonesia', 'ND', 'bg-[#0761C7]', 'Jakarta', 'Hybrid', 'Game UI/UX & Asset Designer Intern', ARRAY['Figma', 'Photoshop', 'Game UI', 'Asset Export', 'Wireframe'], 'Merancang layout antarmuka interaktif game mobile, membuat ikon item, tombol, dan asset sheet yang siap diimpor ke game engine.', 'PG', true, 18, NOW(), NOW()),
('pkl-pg-4', 'Toge Productions', 'TP', 'bg-[#EC4899]', 'Tangerang', 'Remote', '2D Sprite & Pixel Animator Intern', ARRAY['Aseprite', 'Pixel Art', '2D Animation', 'Frame-by-frame'], 'Membuat aset karakter 2D, animasi walk/attack/idle frame-by-frame menggunakan Aseprite, dan menyiapkan sprite sheets untuk integrasi game.', 'PG', true, 19, NOW(), NOW()),
('pkl-pg-5', 'Metra Digital', 'MD', 'bg-[#E4002B]', 'Jakarta', 'Hybrid', 'Multimedia & Motion Graphics Intern', ARRAY['After Effects', 'Premiere Pro', 'Motion Graphics', 'Video Editing'], 'Memproduksi trailer gameplay interaktif, animasi motion graphics promosi digital, dan aset visual multimedia untuk rilisan gim lokal.', 'PG', true, 20, NOW(), NOW());
